# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1060, 843)
        MainWindow.setMinimumSize(QtCore.QSize(1060, 843))
        MainWindow.setMaximumSize(QtCore.QSize(1060, 843))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1031, 811))
        self.tabWidget.setMinimumSize(QtCore.QSize(1031, 811))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 140, 1001, 411))
        self.groupBox_6.setMinimumSize(QtCore.QSize(1001, 411))
        self.groupBox_6.setObjectName("groupBox_6")
        self.table_task = QtWidgets.QTableWidget(self.groupBox_6)
        self.table_task.setGeometry(QtCore.QRect(10, 31, 981, 371))
        self.table_task.setMinimumSize(QtCore.QSize(981, 371))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.table_task.setFont(font)
        self.table_task.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_task.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_task.setObjectName("table_task")
        self.table_task.setColumnCount(4)
        self.table_task.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_task.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_task.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_task.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_task.setHorizontalHeaderItem(3, item)
        self.table_task.horizontalHeader().setDefaultSectionSize(200)
        self.table_task.verticalHeader().setVisible(False)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(9, 10, 731, 131))
        self.groupBox_5.setMinimumSize(QtCore.QSize(731, 130))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setMinimumSize(QtCore.QSize(200, 34))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cb_security = QtWidgets.QComboBox(self.groupBox_5)
        self.cb_security.setMinimumSize(QtCore.QSize(250, 30))
        self.cb_security.setObjectName("cb_security")
        self.gridLayout.addWidget(self.cb_security, 0, 1, 1, 1)
        self.btn_grapdata = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_grapdata.setMinimumSize(QtCore.QSize(211, 111))
        self.btn_grapdata.setObjectName("btn_grapdata")
        self.gridLayout.addWidget(self.btn_grapdata, 0, 2, 3, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setMinimumSize(QtCore.QSize(200, 32))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.gui_startdate = QtWidgets.QDateEdit(self.groupBox_5)
        self.gui_startdate.setMinimumSize(QtCore.QSize(249, 30))
        self.gui_startdate.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.gui_startdate.setObjectName("gui_startdate")
        self.gridLayout.addWidget(self.gui_startdate, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setMinimumSize(QtCore.QSize(200, 33))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.gui_enddate = QtWidgets.QDateEdit(self.groupBox_5)
        self.gui_enddate.setMinimumSize(QtCore.QSize(249, 30))
        self.gui_enddate.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.gui_enddate.setObjectName("gui_enddate")
        self.gridLayout.addWidget(self.gui_enddate, 2, 1, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 560, 1001, 192))
        self.textBrowser_2.setMinimumSize(QtCore.QSize(991, 192))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_stock_manage = QtWidgets.QWidget()
        self.tab_stock_manage.setObjectName("tab_stock_manage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_stock_manage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_stock_manage)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_security = QtWidgets.QTableWidget(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.table_security.setFont(font)
        self.table_security.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_security.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_security.setObjectName("table_security")
        self.table_security.setColumnCount(2)
        self.table_security.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_security.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_security.setHorizontalHeaderItem(1, item)
        self.table_security.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table_security)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.btn_delete = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_delete.setEnabled(True)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setEnabled(False)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setLineWidth(0)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_stock_manage, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Raymond的小工具"))
        self.groupBox_6.setTitle(_translate("MainWindow", "任务列表"))
        item = self.table_task.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "日期"))
        item = self.table_task.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "股票代码"))
        item = self.table_task.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "股票名称"))
        item = self.table_task.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "动作"))
        self.label.setText(_translate("MainWindow", "选择股票"))
        self.btn_grapdata.setText(_translate("MainWindow", "开始抓取数据"))
        self.label_2.setText(_translate("MainWindow", "开始时间"))
        self.gui_startdate.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_3.setText(_translate("MainWindow", "结束时间"))
        self.gui_enddate.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. 本软件提供批量从港交所获取数据的功能，其他功能，如股票登记和统计图，请继续使用网页版本。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. 按照计划本软件将会提供网页版的所有功能。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. 如需人工服务，请致电+86 13714145561，并且提供“BBQ Code”</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "抓取数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "统计图"))
        item = self.table_security.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "股票代码"))
        item = self.table_security.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "股票民称"))
        self.pushButton.setText(_translate("MainWindow", "新增"))
        self.pushButton_2.setText(_translate("MainWindow", "编辑"))
        self.btn_delete.setText(_translate("MainWindow", "删除"))
        self.groupBox.setTitle(_translate("MainWindow", "帮助"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">要跟踪一个股票，首先就是要在数据库里登记这个股票的基本信息，其中需要要输入以下信息：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. 股票代码 </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. 股票名称</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">股票一旦登记成功，股票代码是不能修改的，股票名称没有这个限制，可以在使用的过程中随意修改</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">如果你选择删除某一只股票，则这个股票的所有数据都会一并从数据库里删除</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_stock_manage), _translate("MainWindow", "股票管理"))
        self.action_2.setText(_translate("MainWindow", "退出"))

